# Generated by Django 5.2.7 on 2025-10-30 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Extradition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_point', models.CharField(max_length=255, verbose_name='Пункт выдачи')),
                ('confirmed', models.BooleanField(default=False, verbose_name='Подтверждено получателем')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_extraditions', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник, выдавший посылку')),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extraditions', to='myprofile.receipt', verbose_name='Чек')),
                ('track_codes', models.ManyToManyField(related_name='extraditions', to='myprofile.trackcode', verbose_name='Трек-коды')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraditions', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Выдача посылки',
                'verbose_name_plural': 'Выдачи посылок',
            },
        ),
        migrations.CreateModel(
            name='ExtraditionReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_point', models.CharField(max_length=255, verbose_name='Пункт выдачи')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата выдачи')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Выдал сотрудник')),
                ('receipt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extradition_receipt', to='myprofile.receipt', verbose_name='Чек')),
            ],
        ),
    ]
